name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change 'main' if your primary branch is different (e.g., 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # You can adjust this Node.js version if needed

      - name: Install dependencies
        run: npm install # Or 'yarn install' if you use Yarn

      - name: Build project # Build your React app and pass the secret variables
        run: npm run build # Uses the 'build' script from your package.json
        env: # These environment variables will be available during the build
          # IMPORTANT: For Create React App, environment variables must start with REACT_APP_
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}

      - name: Deploy to GitHub Pages # Deploy the built application to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Create React App's build output folder is 'build'
          # If you're deploying to a custom branch (e.g., 'gh-pages'), uncomment this:
          # publish_branch: gh-pages
